version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=postgresql://postgres:mysecret@postgres:5432/postgres
    depends_on:
      - postgres

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.web
      args:
        - DATABASE_URL=postgresql://postgres:mysecret@postgres:5432/postgres
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://postgres:mysecret@postgres:5432/postgres
    depends_on:
      - postgres

  ws:
    build:
      context: .
      dockerfile: docker/Dockerfile.ws
    ports:
      - 8081:8081
    environment:
      - DATABASE_URL=postgresql://postgres:mysecret@postgres:5432/postgres
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecret
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
