FROM oven/bun:latest

WORKDIR /usr/src/mono

RUN apt-get update -y && apt-get install -y openssl

ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}

COPY ./packages ./packages
COPY ./bun.lockb ./bun.lockb

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/web ./apps/web

RUN bun install --frozen-lockfile
RUN bun run db:generate
# RUN DATABASE_URL=${DATABASE_URL} bun run build

EXPOSE 3000

CMD [ "bun", "run", "start:web" ]

# DOCKER-FILE BECOMES TRICKY WHEN NEXTJS NEEDS TO TALK TO THE DB DURING THE BUILD PHASE