version: "2.40.0"
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
    - POSTGRES_PASSWORD=mysecret

  dc-app:
    build:
      network: host
      context: ./
      dockerfile: Dockerfile

    environment:
      - DATABASE_URL=postgresql://postgres:mysecret@postgres:5432/postgres

    ports:
      - 3000:3000

    depends_on:
      - postgres
